# Generated by Django 4.2.1 on 2023-06-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
