# Generated by Django 4.2.1 on 2023-06-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0002_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id_producto',
            new_name='id',
        ),
    ]
